# A Crash Course in Python for Scientists

### Why Python?
Python is the programming language of choice for many scientists to a large degree because it offers a great deal of power to analyze and model scientific data with relatively little overhead in terms of learning, installation or development time. It is a language you can pick up in a weekend, and use for the rest of one's life.


Please note, is not meant to be a comprehensive overview of Python or programming in general, if you have no programming experience,I suggest to read [Python for You and Me.](https://733amir.github.io/python-for-you-and-me/)

#### Topic
* Data types
    * Numbers
    * Strings
    * Printing
    * Lists
    * Dictionaries
    * Booleans
    * Tuples 
    * Sets
* Comparison Operators
* if,elif, else Statements
* for Loops
* while Loops
* range()
* list comprehension
* map and filter
* functions
* lambda expressions
* map and filter
____

## Data types

### Numbers and Arithmetics

In [1]:
2 + 2

4

In [2]:
2 * 3

6

In [3]:
1 / 2 

0.5

In [4]:
7 // 2

3

In [5]:
4 ** 3

64

In [6]:
23 % 4

3

In [7]:
var = 2 
var2 = 54

In [8]:
var3 = var2 - var

In [9]:
var3

52

### String 

In [10]:
'Hello world' 

'Hello world'

In [11]:
"Hello world"

'Hello world'

### Print

In [12]:
print('Hello world')

Hello world


In [13]:
name = 'sadegh'
course = 'Machine learning'

In [14]:
print('My name is {} this is a {} course'.format(name,course))

My name is sadegh this is a Machine learning course


In [15]:
print('My name is {myname} this is a {name_course} course'.format(name_course = course, myname = name))

My name is sadegh this is a Machine learning course


### Lists

In [16]:
[1, 2, 3]

[1, 2, 3]

In [17]:
[1 , [3, 4], 'hello :)']

[1, [3, 4], 'hello :)']

In [18]:
myList = [1 ,2 ,3, 4, 5, 6]

In [19]:
myList.append(12)

In [20]:
myList

[1, 2, 3, 4, 5, 6, 12]

In [21]:
myList[2] 

3

In [22]:
myList[1:3]  

[2, 3]

In [23]:
myList [1:]

[2, 3, 4, 5, 6, 12]

In [24]:
myList[0:5:2]

[1, 3, 5]

In [25]:
myList[-1]

12

In [26]:
myList[0]

1

In [27]:
myList[0] = 'wow'

In [28]:
myList

['wow', 2, 3, 4, 5, 6, 12]

In [29]:
myList = [[[1, 2 ,3], [4, 5, 6], [7, 8, 9]], [[-1, -2, -3], [-4, -5, -6], [-7, -8 , -9]]]

In [30]:
myList[0][2][2]

9

In [31]:
np.array(myList)

NameError: name 'np' is not defined

### Dictionaries

In [32]:
dictinary = {'key1':'item1','key2':'item2'} 

In [33]:
dictinary

{'key1': 'item1', 'key2': 'item2'}

In [34]:
dictinary['key1']

'item1'

### Tuples

In [35]:
t = (1, 2, 3)

In [36]:
t[0]

1

In [37]:
t[0] = 5

TypeError: 'tuple' object does not support item assignment

## Comparison Operators ## Logic Operators
 bigger than, les than, equal and ,,,
 
 and, or 

## if,elif, else Statements

In [38]:
if 23 < 34:
    print('hello')

hello


In [39]:
if 5 < 2:
    print('first')
else:
    print('second')

second


In [40]:
if 1 == 2:
    print('first')
elif 3 == 3:
    print('second')
else:
    print('third')

second


## for Loops

In [41]:
seq = ['hello', 'python', 'good']

In [42]:
for i in seq:
    print(i)

hello
python
good


In [43]:
seq = [1, 2, 3, 4, 5]

In [44]:
for i in seq:
    print (i ** 2)

1
4
9
16
25


### range()

In [45]:
range(5)

range(0, 5)

In [46]:
list(range(5))

[0, 1, 2, 3, 4]

In [47]:
for i in range(2,5):
    print(i)

2
3
4


## while Loops

In [48]:
i = 1
while i < 5:
    print('number i is: {}'.format(i))
    i += 1

number i is: 1
number i is: 2
number i is: 3
number i is: 4


## list comprehension

In [49]:
x = [1, 2, 3, 4]

In [50]:
output = list()
#output = []
for i in x :
    output.append(i + 2)
output

[3, 4, 5, 6]

In [51]:
[i + 2 for i in x]

[3, 4, 5, 6]

## functions



In [3]:
def func(param1):
    print(param1)


In [5]:
func(param1='hello')

hello


In [6]:
def func2(number):
    return number * 2

In [7]:
func2(2)

4


## map and filter


In [8]:
seq = [1,2,3,4,5]

In [11]:
map(func2,seq)

In [13]:

list(map(func2,seq))


[2, 4, 6, 8, 10]

### lambda expressions

In [14]:
list(map(lambda var: var*2,seq))

[2, 4, 6, 8, 10]

In [15]:
filter(lambda item: item%2 == 0,seq)

In [17]:
list(filter(lambda item: item%2 == 0,seq))

[2, 4]

## Other


# NumPy 

NumPy is a Linear Algebra Library for Python.

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy dimensions are called axes. The number of axes is rank.
For example, the coordinates of a point in 3D space [1, 2, 1] is an array of rank 1, because it has one axis. That axis has a length of 3. In the example pictured below, the array has rank 2 (it is 2-dimensional).

Numpy is also incredibly fast, as it has bindings to C libraries.

For easy installing Numpy:
```bash 
sudo pip install numpy
```


### NumPy array 



In [52]:
import numpy as np 

a = [1,2,3]

a

[1, 2, 3]

In [53]:
b = np.array(a)
b

array([1, 2, 3])

In [54]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

### zeros , ones and eye


###### np.zeros

Return a new array of given shape and type, filled with zeros.

In [56]:
np.zeros(2, dtype=float)

array([ 0.,  0.])

In [57]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

###### ones
Return a new array of given shape and type, filled with ones.

In [58]:
np.ones(3, )

array([ 1.,  1.,  1.])

###### eye

Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [59]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

###### linspace

Returns num evenly spaced samples, calculated over the interval [start, stop].

In [60]:
np.linspace(1, 11, 3)

array([  1.,   6.,  11.])

### Random number and matrix

###### rand

Random values in a given shape.

In [61]:
np.random.rand(2)

array([ 0.98944695,  0.15204822])

In [62]:
np.random.rand(2,3,4)

array([[[ 0.58762541,  0.54866977,  0.49530741,  0.95368946],
        [ 0.64593345,  0.54928187,  0.50802892,  0.28852346],
        [ 0.25626359,  0.48941596,  0.16215579,  0.09143872]],

       [[ 0.17206198,  0.80906599,  0.61610376,  0.02106817],
        [ 0.47015081,  0.93353851,  0.74257841,  0.13820162],
        [ 0.51805814,  0.98518464,  0.03489848,  0.94352027]]])

###### randn

Return a sample (or samples) from the "standard normal" distribution.

- andom.standard_normal    Similar, but takes a tuple as its argument. 


In [63]:
np.random.randn(2,3)

array([[ 0.85549542, -1.09447794, -0.98193665],
       [-1.85804795, -0.42809007, -1.14910224]])

###### random

Return random floats in the half-open interval [0.0, 1.0).

In [64]:
np.random.random()

0.027643775260122516

###### randint


Return n random integers (by default one integer) from low (inclusive) to high (exclusive).

In [65]:
np.random.randint(1,50,10)

array([31, 46, 30, 22, 17, 21, 45,  9, 24,  5])

In [66]:
np.random.randint(1,40)

6

#### Shape and Reshape

###### shape return the shape of data and reshape returns an array containing the same data with a new shape

In [67]:
zero = np.zeros([3,4])
print(zero , '   ' ,'shape of a :' , zero.shape)
zero = zero.reshape([2,6])
print()
print(zero)


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]     shape of a : (3, 4)

[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]


## Basic Operation

#### Element wise product and matrix product

In [68]:
number = np.array([[1,2,],[3,4]])
number2 = np.array([[1,3],[2,1]])

print('element wise product :\n',number * number2 )
print('matrix product :\n',number.dot(number2))     ## also can use : np.dot(number, number2)

element wise product :
 [[1 6]
 [6 4]]
matrix product :
 [[ 5  5]
 [11 13]]


### min max argmin argmax mean 

In [69]:
numbers = np.random.randint(1,100, 10)
print(numbers)
print('max is :', numbers.max())
print('index of max :', numbers.argmax())
print('min is :', numbers.min())
print('index of min :', numbers.argmin())
print('mean :', numbers.mean())

[64 35 41 81  2 45 24 68 96 42]
max is : 96
index of max : 8
min is : 2
index of min : 4
mean : 49.8


## Universal function 

numpy also has some funtion for mathmatical operation like exp, log, sqrt, abs and etc .

for find more function click [here](https://docs.scipy.org/doc/numpy/reference/ufuncs.html) 


In [70]:
number = np.arange(1,10).reshape(3,3)
print(number)
print()
print('exp:\n', np.exp(number))
print()
print('sqrt:\n',np.sqrt(number))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

exp:
 [[  2.71828183e+00   7.38905610e+00   2.00855369e+01]
 [  5.45981500e+01   1.48413159e+02   4.03428793e+02]
 [  1.09663316e+03   2.98095799e+03   8.10308393e+03]]

sqrt:
 [[ 1.          1.41421356  1.73205081]
 [ 2.          2.23606798  2.44948974]
 [ 2.64575131  2.82842712  3.        ]]


##### dtype

In [71]:
numbers.dtype

dtype('int64')

# No copy & Shallow copy & Deep copy


* ### No copy 
   ###### Simple assignments make no copy of array objects or of their data.

In [72]:
number = np.arange(0,20)
number2 = number 
print (number is number2 , id(number), id(number2))
print(number)
number2.shape = (4,5)
print(number)

True 140247795698624 140247795698624
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


* ### Shallow copy

  Different array objects can share the same data. The view method creates a new array object that looks at the same data.

In [73]:
number = np.arange(0,20)
number2 = number.view()
print (number is number2 , id(number), id(number2))

False 140247795704256 140247795705216


In [74]:
number2.shape = (5,4)
print('number2 shape:', number2.shape,'\nnumber shape:', number.shape)

number2 shape: (5, 4) 
number shape: (20,)


In [75]:
print('befor:', number)
number2[0][0] = 2222
print()
print('after:', number)

befor: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

after: [2222    1    2    3    4    5    6    7    8    9   10   11   12   13   14
   15   16   17   18   19]


* ### Deep copy 

  The copy method makes a complete copy of the array and its data.

In [76]:
number = np.arange(0,20)
number2 = number.copy()
print (number is number2 , id(number), id(number2))


False 140247795705696 140247795705616


In [77]:
print('befor:', number)
number2[0] = 10
print()
print('after:', number)
print()
print('number2:',number2)

befor: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

after: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

number2: [10  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


# Broadcating

 ###### One of important concept to understand numpy is Broadcasting 
 It's very useful for performancing mathmaica operation beetween arrays of different shape.
         

In [78]:
number = np.arange(1,11)
num = 2 
print(' number =', number)
print('\n number .* num =',number * num)

 number = [ 1  2  3  4  5  6  7  8  9 10]

 number .* num = [ 2  4  6  8 10 12 14 16 18 20]


In [79]:
number = np.arange(1,10).reshape(3,3)
number2 = np.arange(1,4).reshape(1,3)
number * number2

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [80]:
number = np.array([1,2,3])
print('number =', number)
print('\nnumber =', number + 100)

number = [1 2 3]

number = [101 102 103]


In [81]:
number = np.arange(1,10).reshape(3,3)
number2 = np.arange(1,4)
print('number: \n', number)
add = number + number2 
print()
print('number2: \n ', number2)
print()
print('add: \n', add)

number: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

number2: 
  [1 2 3]

add: 
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


## If you still doubt Why we use Python and NumPy see it. 😉
 

In [82]:
from time import time
a = np.random.rand(8000000, 1)
c = 0
tic = time()
for i in range(len(a)):
    c +=(a[i][0] * a[i][0])
          
print ('output1:', c)
tak = time()

print('multiply 2 matrix with loop: ', tak - tic)

tic = time()
print('output2:', np.dot(a.T, a))
tak = time()


print('multiply 2 matrix with numpy func: ', tak - tic)

output1: 2666048.98309
multiply 2 matrix with loop:  5.055637836456299
output2: [[ 2666048.9830859]]
multiply 2 matrix with numpy func:  0.00422358512878418


### I tried to write essential things in numpy that you can start to code and enjpy it but there are many function  that i don't write in this book if you neet more informatino click [here](https://docs.scipy.org/doc/numpy-dev/reference/routines.html#routines)